# Generated by Django 2.2 on 2019-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=50)),
                ('recipeCalories', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('serving', models.CharField(max_length=50)),
                ('pork', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('meat', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
            ],
        ),
    ]
