# Generated by Django 2.1.1 on 2019-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=50)),
                ('recipeCalories', models.IntegerField(default=0)),
                ('pork', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('gluten', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('meat', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('containsMilk', models.BooleanField(default=False)),
                ('containsMilkSubstitute', models.BooleanField(default=False)),
            ],
        ),
    ]
