# Generated by Django 2.2 on 2019-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='containsMilk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='containsMilkSubstitute',
            field=models.BooleanField(default=False),
        ),
    ]
