# Generated by Django 2.1.1 on 2019-04-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0002_auto_20190414_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeCalories',
            field=models.IntegerField(default=0),
        ),
    ]
