# Generated by Django 2.1.1 on 2019-05-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0003_auto_20190430_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='fish',
            field=models.BooleanField(default=False),
        ),
    ]
