# Generated by Django 2.1.1 on 2019-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0004_recipe_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='serving',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCalories',
            field=models.CharField(max_length=50),
        ),
    ]
