# Generated by Django 2.1.1 on 2019-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodList', '0005_auto_20190503_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeCalories',
            field=models.IntegerField(default=0),
        ),
    ]
